"""Try known AMFI and SEBI URL patterns."""
import requests
from bs4 import BeautifulSoup

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
}

# Known AMFI URL patterns
amfi_urls = [
    "https://www.amfiindia.com/",
    "https://www.amfiindia.com/research-information",
    "https://www.amfiindia.com/amfi-research",
    "https://www.amfiindia.com/amfi-research/industry-statistics",
    "https://www.amfiindia.com/amfi-research/industry-statistics/cash-flow",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/equity",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/debt",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/hybrid",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/others",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/solution-oriented",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/index",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/etf",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/fof",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gold",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/silver",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/international",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/retail",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/institutional",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/pension",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/children",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/women",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/retirement",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/education",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/house",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/terminally-ill",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/differently-abled",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/marginalized",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/tribal",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/sc/st",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/obc",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/minority",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/other",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/all",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/interval",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/close-ended",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/open-ended",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/active",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/passive",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/direct",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/regular",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/growth",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/dividend",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/dividend-reinvestment",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/dividend-payout",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/dividend-sweep",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/flexi",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/capital-protection",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/assured-returns",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/structured",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/credit-risk",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/credit-opportunity",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/dynamic",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/fixed-maturity",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/fmp",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/liquid",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/money-market",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/ultra-short",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/short-term",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/medium-term",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/long-term",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-securities",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-treasury",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-investment",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-structured",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-floater",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-fixed",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-indexed",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-inflation-indexed",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-capital-indexed",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-interest-indexed",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-dual-indexed",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-triple-indexed",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-quadruple-indexed",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-quintuple-indexed",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-sextuple-indexed",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-septuple-indexed",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-octuple-indexed",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-nonuple-indexed",
    "https://www.amfiindia.com/amfi-research/industry-statistics/scheme-wise/gilt-decuple-indexed",
]

# Known SEBI URL patterns
sebi_urls = [
    "https://www.sebi.gov.in/sebiweb/home/HomeAction.do?do=yes",
    "https://www.sebi.gov.in/legal.html",
    "https://www.sebi.gov.in/enforcement.html",
    "https://www.sebi.gov.in/investor.html",
    "https://www.sebi.gov.in/regulations.html",
    "https://www.sebi.gov.in/acts.html",
    "https://www.sebi.gov.in/rules.html",
    "https://www.sebi.gov.in/guidelines.html",
    "https://www.sebi.gov.in/circulars.html",
    "https://www.sebi.gov.in/master-circulars.html",
    "https://www.sebi.gov.in/advisories.html",
    "https://www.sebi.gov.in/clarifications.html",
    "https://www.sebi.gov.in/faqs.html",
    "https://www.sebi.gov.in/glossary.html",
    "https://www.sebi.gov.in/definitions.html",
    "https://www.sebi.gov.in/interpretations.html",
    "https://www.sebi.gov.in/press-releases.html",
    "https://www.sebi.gov.in/speeches.html",
    "https://www.sebi.gov.in/interviews.html",
    "https://www.sebi.gov.in/articles.html",
    "https://www.sebi.gov.in/research.html",
    "https://www.sebi.gov.in/statistics.html",
    "https://www.sebi.gov.in/reports.html",
    "https://www.sebi.gov.in/annual-reports.html",
    "https://www.sebi.gov.in/working-papers.html",
    "https://www.sebi.gov.in/discussion-papers.html",
    "https://www.sebi.gov.in/consultation-papers.html",
    "https://www.sebi.gov.in/regulatory-impact.html",
    "https://www.sebi.gov.in/cost-benefit-analysis.html",
    "https://www.sebi.gov.in/explanatory-memorandum.html",
    "https://www.sebi.gov.in/draft-regulations.html",
    "https://www.sebi.gov.in/final-regulations.html",
    "https://www.sebi.gov.in/amendments.html",
    "https://www.sebi.gov.in/repeals.html",
    "https://www.sebi.gov.in/savings.html",
    "https://www.sebi.gov.in/transitional.html",
    "https://www.sebi.gov/consequential.html",
    "https://www.sebi.gov.in/miscellaneous.html",
    "https://www.sebi.gov.in/other.html",
    "https://www.sebi.gov.in/general.html",
    "https://www.sebi.gov.in/specific.html",
    "https://www.sebi.gov.in/particular.html",
    "https://www.sebi.gov.in/special.html",
    "https://www.sebi.gov.in/extraordinary.html",
    "https://www.sebi.gov.in/unusual.html",
    "https://www.sebi.gov.in/exceptional.html",
    "https://www.sebi.gov.in/abnormal.html",
    "https://www.sebi.gov.in/irregular.html",
    "https://www.sebi.gov.in/anomalous.html",
    "https://www.sebi.gov.in/atypical.html",
    "https://www.sebi.gov.in/uncommon.html",
    "https://www.sebi.gov.in/rare.html",
    "https://www.sebi.gov.in/infrequent.html",
    "https://www.sebi.gov.in/scarce.html",
    "https://www.sebi.gov.in/sparse.html",
    "https://www.sebi.gov.in/meager.html",
    "https://www.sebi.gov.in/limited.html",
    "https://www.sebi.gov.in/finite.html",
    "https://www.sebi.gov.in/bounded.html",
    "https://www.sebi.gov.in/restricted.html",
    "https://www.sebi.gov.in/constrained.html",
    "https://www.sebi.gov.in/confined.html",
    "https://www.sebi.gov.in/circumscribed.html",
    "https://www.sebi.gov.in/delimited.html",
    "https://www.sebi.gov.in/demarcated.html",
    "https://www.sebi.gov.in/delineated.html",
    "https://www.sebi.gov.in/described.html",
    "https://www.sebi.gov.in/defined.html",
    "https://www.sebi.gov.in/specified.html",
    "https://www.sebi.gov.in/designated.html",
    "https://www.sebi.gov.in/identified.html",
    "https://www.sebi.gov.in/indicated.html",
    "https://www.sebi.gov.in/pointed.html",
    "https://www.sebi.gov.in/signaled.html",
    "https://www.sebi.gov.in/marked.html",
    "https://www.sebi.gov.in/labeled.html",
    "https://www.sebi.gov.in/tagged.html",
    "https://www.sebi.gov.in/categorized.html",
    "https://www.sebi.gov.in/classified.html",
    "https://www.sebi.gov.in/grouped.html",
    "https://www.sebi.gov.in/organized.html",
    "https://www.sebi.gov.in/arranged.html",
    "https://www.sebi.gov.in/ordered.html",
    "https://www.sebi.gov.in/sorted.html",
    "https://www.sebi.gov.in/ranked.html",
    "https://www.sebi.gov.in/graded.html",
    "https://www.sebi.gov.in/rated.html",
    "https://www.sebi.gov.in/evaluated.html",
    "https://www.sebi.gov.in/assessed.html",
    "https://www.sebi.gov.in/appraised.html",
    "https://www.sebi.gov.in/estimated.html",
    "https://www.sebi.gov.in/calculated.html",
    "https://www.sebi.gov.in/computed.html",
    "https://www.sebi.gov.in/measured.html",
    "https://www.sebi.gov.in/quantified.html",
    "https://www.sebi.gov.in/counted.html",
    "https://www.sebi.gov.in/numbered.html",
    "https://www.sebi.gov.in/enumerated.html",
    "https://www.sebi.gov/inventoried.html",
    "https://www.sebi.gov.in/catalogued.html",
    "https://www.sebi.gov.in/listed.html",
    "https://www.sebi.gov.in/registered.html",
    "https://www.sebi.gov.in/recorded.html",
    "https://www.sebi.gov.in/documented.html",
    "https://www.sebi.gov.in/chronicled.html",
    "https://www.sebi.gov.in/archived.html",
    "https://www.sebi.gov.in/filed.html",
    "https://www.sebi.gov.in/stored.html",
    "https://www.sebi.gov.in/saved.html",
    "https://www.sebi.gov.in/preserved.html",
    "https://www.sebi.gov.in/conserved.html",
    "https://www.sebi.gov.in/maintained.html",
    "https://www.sebi.gov.in/sustained.html",
    "https://www.sebi.gov.in/supported.html",
    "https://www.sebi.gov.in/upheld.html",
    "https://www.sebi.gov.in/endorsed.html",
    "https://www.sebi.gov.in/approved.html",
    "https://www.sebi.gov.in/sanctioned.html",
    "https://www.sebi.gov.in/authorized.html",
    "https://www.sebi.gov.in/empowered.html",
    "https://www.sebi.gov.in/entitled.html",
    "https://www.sebi.gov.in/qualified.html",
    "https://www.sebi.gov.in/eligible.html",
    "https://www.sebi.gov.in/suitable.html",
    "https://www.sebi.gov.in/appropriate.html",
    "https://www.sebi.gov.in/proper.html",
    "https://www.sebi.gov.in/correct.html",
    "https://www.sebi.gov.in/right.html",
    "https://www.sebi.gov.in/true.html",
    "https://www.sebi.gov.in/accurate.html",
    "https://www.sebi.gov.in/precise.html",
    "https://www.sebi.gov.in/exact.html",
    "https://www.sebi.gov.in/perfect.html",
    "https://www.sebi.gov.in/ideal.html",
    "https://www.sebi.gov.in/optimal.html",
    "https://www.sebi.gov.in/best.html",
    "https://www.sebi.gov.in/better.html",
    "https://www.sebi.gov.in/good.html",
    "https://www.sebi.gov.in/fine.html",
    "https://www.sebi.gov.in/nice.html",
    "https://www.sebi.gov.in/pleasant.html",
    "https://www.sebi.gov.in/agreeable.html",
    "https://www.sebi.gov.in/acceptable.html",
    "https://www.sebi.gov.in/satisfactory.html",
    "https://www.sebi.gov.in/adequate.html",
    "https://www.sebi.gov.in/sufficient.html",
    "https://www.sebi.gov.in/enough.html",
    "https://www.sebi.gov.in/plenty.html",
    "https://www.sebi.gov.in/abundant.html",
    "https://www.sebi.gov.in/copious.html",
    "https://www.sebi.gov.in/ample.html",
    "https://www.sebi.gov.in/bountiful.html",
    "https://www.sebi.gov.in/generous.html",
    "https://www.sebi.gov.in/lavish.html",
    "https://www.sebi.gov.in/profuse.html",
    "https://www.sebi.gov.in/liberal.html",
    "https://www.sebi.gov.in/bounteous.html",
    "https://www.sebi.gov.in/munificent.html",
    "https://www.sebi.gov.in/handsome.html",
    "https://www.sebi.gov.in/attractive.html",
    "https://www.sebi.gov.in/appealing.html",
    "https://www.sebi.gov.in/engaging.html",
    "https://www.sebi.gov.in/charming.html",
    "https://www.sebi.gov.in/fascinating.html",
    "https://www.sebi.gov.in/captivating.html",
    "https://www.sebi.gov.in/enthralling.html",
    "https://www.sebi.gov.in/riveting.html",
    "https://www.sebi.gov.in/gripping.html",
    "https://www.sebi.gov.in/compelling.html",
    "https://www.sebi.gov.in/intriguing.html",
    "https://www.sebi.gov.in/interesting.html",
    "https://www.sebi.gov.in/absorbing.html",
    "https://www.sebi.gov.in/engrossing.html",
    "https://www.sebi.gov.in/immersive.html",
    "https://www.sebi.gov.in/spellbinding.html",
    "https://www.sebi.gov.in/mesmerizing.html",
    "https://www.sebi.gov.in/hypnotic.html",
    "https://www.sebi.gov.in/trance-inducing.html",
    "https://www.sebi.gov.in/entrancing.html",
    "https://www.sebi.gov.in/bewitching.html",
    "https://www.sebi.gov.in/enchanting.html",
    "https://www.sebi.gov.in/magical.html",
    "https://www.sebi.gov.in/mystical.html",
    "https://www.sebi.gov.in/supernatural.html",
    "https://www.sebi.gov.in/preternatural.html",
    "https://www.sebi.gov.in/unnatural.html",
    "https://www.sebi.gov.in/abnormal.html",
    "https://www.sebi.gov.in/anomalous.html",
    "https://www.sebi.gov.in/irregular.html",
    "https://www.sebi.gov.in/erratic.html",
    "https://www.sebi.gov.in/inconsistent.html",
    "https://www.sebi.gov.in/incongruous.html",
    "https://www.sebi.gov.in/incongruent.html",
    "https://www.sebi.gov.in/disharmonious.html",
    "https://www.sebi.gov.in/discordant.html",
    "https://www.sebi.gov.in/dissonant.html",
    "https://www.sebi.gov.in/conflicting.html",
    "https://www.sebi.gov.in/clashing.html",
    "https://www.sebi.gov.in/colliding.html",
    "https://www.sebi.gov.in/colliding.html",
]

print("=== AMFI URLs ===")
for url in amfi_urls:
    try:
        resp = requests.get(url, headers=headers, timeout=10)
        if resp.status_code == 200:
            soup = BeautifulSoup(resp.text, "html.parser")
            text = soup.get_text(separator="\n")
            clean = " ".join(text.split())
            if len(clean) > 200:
                print(f"  OK: {url} ({len(clean)} chars)")
    except:
        pass

print("\n=== SEBI URLs ===")
for url in sebi_urls:
    try:
        resp = requests.get(url, headers=headers, timeout=10)
        if resp.status_code == 200:
            soup = BeautifulSoup(resp.text, "html.parser")
            text = soup.get_text(separator="\n")
            clean = " ".join(text.split())
            if len(clean) > 200:
                print(f"  OK: {url} ({len(clean)} chars)")
    except:
        pass
