[server]
fileWatcherType = "none"
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#00D09C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0FFF9"
textColor = "#333333"
